import { NextRequest, NextResponse } from "next/server";
import { getDb } from "@/lib/db";
import { getSession } from "@/lib/auth";
import { autoRunAllTournaments } from "@/lib/scheduled-tournaments";

let _autoRunDone = false;

export async function GET(req: NextRequest) {
  // Auto-run tournaments on first GET (server cold start)
  if (!_autoRunDone) {
    _autoRunDone = true;
    autoRunAllTournaments().catch(() => {});
  }

  const db = getDb();
  const status = req.nextUrl.searchParams.get("status");
  const tier = req.nextUrl.searchParams.get("tier");
  const mode = req.nextUrl.searchParams.get("mode");
  const type = req.nextUrl.searchParams.get("type");

  let query = `
    SELECT t.*,
      (SELECT COUNT(*) FROM tournament_players WHERE tournament_id = t.id) as player_count,
      u.username as created_by_name
    FROM tournaments t
    JOIN users u ON t.created_by = u.id
    WHERE 1=1
  `;
  const params: string[] = [];

  if (status && status !== "all") {
    query += " AND t.status = ?";
    params.push(status);
  }
  if (tier && tier !== "all") {
    query += " AND t.difficulty_tier = ?";
    params.push(tier);
  }
  if (mode && mode !== "all") {
    query += " AND t.mode = ?";
    params.push(mode);
  }
  if (type && type !== "all") {
    query += " AND t.tournament_type = ?";
    params.push(type);
  }

  query += " ORDER BY t.featured DESC, t.created_at DESC LIMIT 100";

  const tournaments = db.prepare(query).all(...params);
  return NextResponse.json({ tournaments });
}

export async function POST(req: NextRequest) {
  const user = await getSession();
  if (!user) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }

  if (user.role !== "admin") {
    return NextResponse.json(
      { error: "Only administrators can create tournaments. Tournaments are auto-generated by the system." },
      { status: 403 }
    );
  }

  try {
    const body = await req.json();
    const { v4: uuidv4 } = await import("uuid");
    const {
      name,
      description = "",
      tournament_type = "daily",
      difficulty_tier = "beginner",
      mode = "accuracy",
      format = "swiss_bracket",
      maxPlayers = 16,
      maps = [],
      swissRounds = 3,
      bracketType = "single_elimination",
      bestOfSwiss = 1,
      bestOfPlayoffs = 3,
      submissionDeadlineHours = 24,
      startsAt,
    } = body;

    if (!name) {
      return NextResponse.json({ error: "Tournament name required" }, { status: 400 });
    }

    const id = uuidv4();
    const db = getDb();

    db.prepare(
      `INSERT INTO tournaments (id, name, description, tournament_type, difficulty_tier, mode, format,
        max_players, maps, swiss_rounds, bracket_type, best_of_swiss, best_of_playoffs,
        submission_deadline_hours, created_by, starts_at, auto_start, featured, status)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, 1, 'registration')`
    ).run(
      id, name, description, tournament_type, difficulty_tier, mode, format,
      maxPlayers, JSON.stringify(maps), swissRounds, bracketType,
      bestOfSwiss, bestOfPlayoffs, submissionDeadlineHours,
      user.id, startsAt || null
    );

    return NextResponse.json({ tournament: { id, name } });
  } catch {
    return NextResponse.json({ error: "Server error" }, { status: 500 });
  }
}
